modLoader="javafml"
loaderVersion="[32,)"
issueTrackerURL="https://github.com/camcamcamcamcam/momentum/issues"
license="https://github.com/camcamcamcamcam/momentum/blob/master/LICENSE.txt"

[[mods]]
    modId="momentum"
    version="1.2.1"
    logoFile="logo.png"
    authors="Cameron, Jackson, Smelly"
    displayName="Momentum"
    description='''
    The Momentum Enchantment
    '''

[[dependencies.momentum]]
    modId="forge"
    mandatory=true
    versionRange="[35.1.37,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.momentum]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3,1.17)"
    ordering="NONE"
    side="BOTH"

[[dependencies.momentum]]
    modId="abnormals_core"
    mandatory=true
    versionRange="[3.0.6,)"
    ordering="AFTER"
    side="BOTH"
